### ISSUE TITLE
Verificar emissão de eventos

### ISSUE THREAD

**Issue by cleitonIntegracao** [konflanzzz/nfe-node-js#1]
[TESTE]
Acredito ser necessário e interessante implementar uma validação de retornos nas emissões de eventos.

**Comment by konflanzzz** [comment]
[TESTE-RESPOSTA] 

Bom Dia!
Já estou trabalhando nesta implementação!

Acredito que logo vamos fazer a atualização contento as novas implementações.

**Comment by konflanzzz** [comment]
Boa Tarde meu caro!

Já implementei o tratamento de erros e validação de retornos nos métodos que realizam as emissões de eventos.

Podes ver aqui: #75e1a997f17f525cc563cf4b57b4228424c4e703

Obrigado por colaborar com meu projeto!
